// Johnson Reviews — content data
window.JR_DATA = {
  issue: { no: 47, date: "APR · MMXXVI", location: "LAGUNA BEACH, CA" },

  reviews: [
    {
      id: "hana-re",
      slug: "hana-re-costa-mesa",
      category: "Restaurants",
      type: "restaurant",
      title: "Hana re",
      subtitle: "A twelve-seat counter, a single chef, and the most precise omakase between LA and San Diego.",
      location: "Costa Mesa, California",
      neighborhood: "East 17th",
      score: 9.4,
      cuisine: "Japanese · Omakase",
      price: "$$$$",
      date: "March 2026",
      visited: "Visited four times",
      wouldReturn: true,
      hero: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=2000&q=80",
      gallery: [
        "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&q=80",
        "https://images.unsplash.com/photo-1534080564583-6be75777b70a?w=1200&q=80",
        "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=1200&q=80",
        "https://images.unsplash.com/photo-1583623025817-d180a2fe131e?w=1200&q=80",
        "https://images.unsplash.com/photo-1559410545-0bdcd187e0a6?w=1200&q=80",
        "https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=1200&q=80"
      ],
      blurb: "There's a reason the list runs three months out.",
      tags: ["Omakase", "Sushi", "Date Night", "Special Occasion"],
      featured: true
    },
    {
      id: "montage-laguna",
      slug: "montage-laguna-beach",
      category: "Hotels",
      type: "hotel",
      title: "Montage Laguna Beach",
      subtitle: "The bluffs, the service, the feeling that someone remembered you from last June.",
      location: "Laguna Beach, California",
      neighborhood: "South Laguna",
      score: 9.1,
      cuisine: "Oceanfront Resort",
      price: "$$$$",
      date: "February 2026",
      visited: "Stayed three nights",
      wouldReturn: true,
      hero: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=2000&q=80",
      gallery: [
        "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&q=80",
        "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=1200&q=80",
        "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200&q=80",
        "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80"
      ],
      blurb: "Service so quiet it's almost invisible.",
      tags: ["Luxury", "Oceanfront", "Spa"],
      featured: true
    },
    {
      id: "mexico-city",
      slug: "mexico-city-seven-days",
      category: "Travel",
      type: "destination",
      title: "Seven Days in Mexico City",
      subtitle: "A week of long lunches, quiet rooftops, and the kind of walking you forget you can do in a city this size.",
      location: "Mexico City, Mexico",
      neighborhood: "Roma Norte · Condesa · Centro",
      score: 9.2,
      cuisine: "Travel Feature",
      price: "—",
      date: "January 2026",
      visited: "Seven days on the ground",
      wouldReturn: true,
      hero: "https://images.unsplash.com/photo-1585464231875-d9ef1f5ad396?w=2000&q=80",
      gallery: [
        "https://images.unsplash.com/photo-1518638150340-f706e86654de?w=1200&q=80",
        "https://images.unsplash.com/photo-1512813195386-6cf811ad3542?w=1200&q=80",
        "https://images.unsplash.com/photo-1585464231875-d9ef1f5ad396?w=1200&q=80",
        "https://images.unsplash.com/photo-1547149900-dd3f9a9f7be8?w=1200&q=80",
        "https://images.unsplash.com/photo-1512813195386-6cf811ad3542?w=1200&q=80",
        "https://images.unsplash.com/photo-1518638150340-f706e86654de?w=1200&q=80"
      ],
      blurb: "The best city for eating in the Americas right now.",
      tags: ["Travel", "City Guide", "Mexico"],
      featured: true
    },
    {
      id: "bestia",
      slug: "bestia-los-angeles",
      category: "Restaurants",
      type: "restaurant",
      title: "Bestia",
      subtitle: "Still worth the drive, still worth the difficulty of the reservation.",
      location: "Los Angeles, California",
      neighborhood: "Arts District",
      score: 8.8,
      cuisine: "Italian",
      price: "$$$",
      date: "March 2026",
      visited: "Visited twice this year",
      wouldReturn: true,
      hero: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=2000&q=80",
      gallery: [
        "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=1200&q=80",
        "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=1200&q=80"
      ],
      blurb: "The pizza alone justifies the parking situation.",
      tags: ["Italian", "Pizza", "Pasta"]
    },
    {
      id: "amalfi",
      slug: "ten-days-amalfi",
      category: "Travel",
      type: "destination",
      title: "Ten Days on the Amalfi Coast",
      subtitle: "We drove the cliff road twice. Once anxious, once delighted.",
      location: "Amalfi, Italy",
      neighborhood: "Positano · Ravello · Amalfi",
      score: 9.0,
      cuisine: "Travel Feature",
      price: "—",
      date: "October 2025",
      visited: "Ten nights across three towns",
      wouldReturn: true,
      hero: "https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?w=2000&q=80",
      gallery: [
        "https://images.unsplash.com/photo-1530521954074-e64f6810b32d?w=1200&q=80",
        "https://images.unsplash.com/photo-1544979590-37e9b47eb705?w=1200&q=80"
      ],
      blurb: "The cliff road is worth the anxiety.",
      tags: ["Italy", "Coast", "Road Trip"]
    },
    {
      id: "kettner",
      slug: "kettner-exchange-san-diego",
      category: "Restaurants",
      type: "restaurant",
      title: "Kettner Exchange",
      subtitle: "The rare restaurant that still feels like a night out and not an obligation.",
      location: "San Diego, California",
      neighborhood: "Little Italy",
      score: 8.4,
      cuisine: "New American",
      price: "$$$",
      date: "February 2026",
      visited: "Visited three times",
      wouldReturn: true,
      hero: "https://images.unsplash.com/photo-1544148103-0773bf10d330?w=2000&q=80",
      gallery: [],
      blurb: "Good cocktails, better patio, surprising depth on the menu.",
      tags: ["New American", "Cocktails", "Patio"]
    },
    {
      id: "san-ysidro",
      slug: "san-ysidro-ranch",
      category: "Hotels",
      type: "hotel",
      title: "San Ysidro Ranch",
      subtitle: "A hundred-year-old cottage property in the Montecito foothills. Still one.",
      location: "Montecito, California",
      neighborhood: "Upper Montecito",
      score: 9.3,
      cuisine: "Cottage Resort",
      price: "$$$$",
      date: "December 2025",
      visited: "Two nights",
      wouldReturn: true,
      hero: "https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=2000&q=80",
      gallery: [],
      blurb: "The cottage is the point. The restaurant is a bonus.",
      tags: ["Luxury", "Romantic", "Cottage"]
    },
    {
      id: "providence",
      slug: "providence-los-angeles",
      category: "Restaurants",
      type: "restaurant",
      title: "Providence",
      subtitle: "Seafood precision at a level that stops conversation.",
      location: "Los Angeles, California",
      neighborhood: "Hancock Park",
      score: 9.0,
      cuisine: "Seafood · Tasting",
      price: "$$$$",
      date: "January 2026",
      visited: "Visited twice",
      wouldReturn: true,
      hero: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=2000&q=80",
      gallery: [],
      blurb: "Cimarusti is still the best in the city at what he does.",
      tags: ["Seafood", "Tasting Menu", "Fine Dining"]
    },
    {
      id: "oaxaca",
      slug: "oaxaca-long-weekend",
      category: "Travel",
      type: "destination",
      title: "A Long Weekend in Oaxaca",
      subtitle: "Four days of mole, mezcal, and the best street markets in Mexico.",
      location: "Oaxaca, Mexico",
      neighborhood: "Centro Histórico",
      score: 9.1,
      cuisine: "Travel Feature",
      price: "—",
      date: "November 2025",
      visited: "Four nights",
      wouldReturn: true,
      hero: "https://images.unsplash.com/photo-1518659526054-190340b32735?w=2000&q=80",
      gallery: [],
      blurb: "Go hungry. Leave hungrier.",
      tags: ["Mexico", "Food Travel", "Culture"]
    },
    {
      id: "auberge",
      slug: "auberge-du-soleil",
      category: "Hotels",
      type: "hotel",
      title: "Auberge du Soleil",
      subtitle: "The view from the terrace is still doing most of the work. That's fine.",
      location: "Rutherford, California",
      neighborhood: "Napa Valley",
      score: 8.7,
      cuisine: "Valley Resort",
      price: "$$$$",
      date: "September 2025",
      visited: "Two nights",
      wouldReturn: true,
      hero: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=2000&q=80",
      gallery: [],
      blurb: "Go for the terrace. Stay for the bread service.",
      tags: ["Napa", "View", "Fine Dining"]
    },
    {
      id: "hiroshi",
      slug: "hiroshi-newport-beach",
      category: "Restaurants",
      type: "restaurant",
      title: "Hiroshi",
      subtitle: "The less-known Japanese counter in Newport that quietly rivals anything north.",
      location: "Newport Beach, California",
      neighborhood: "Corona del Mar",
      score: 8.6,
      cuisine: "Japanese",
      price: "$$$",
      date: "March 2026",
      visited: "Visited twice",
      wouldReturn: true,
      hero: "https://images.unsplash.com/photo-1615361200141-f45040f367be?w=2000&q=80",
      gallery: [],
      blurb: "No fanfare, no reservations online, just precision.",
      tags: ["Japanese", "Sushi", "Hidden"]
    },
    {
      id: "tokyo",
      slug: "tokyo-eight-days",
      category: "Travel",
      type: "destination",
      title: "Eight Days in Tokyo",
      subtitle: "A working itinerary, not a greatest-hits list. The neighborhoods we'd return to first.",
      location: "Tokyo, Japan",
      neighborhood: "Shibuya · Nakameguro · Ginza",
      score: 9.5,
      cuisine: "Travel Feature",
      price: "—",
      date: "August 2025",
      visited: "Eight nights",
      wouldReturn: true,
      hero: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=2000&q=80",
      gallery: [],
      blurb: "Still the standard. Still no one comes close.",
      tags: ["Japan", "City Guide", "Food Travel"]
    }
  ],

  locations: [
    { name: "Orange County", count: 84, region: "California" },
    { name: "Los Angeles", count: 112, region: "California" },
    { name: "San Diego", count: 46, region: "California" },
    { name: "Napa & Sonoma", count: 28, region: "California" },
    { name: "Mexico City", count: 21, region: "Mexico" },
    { name: "Tokyo", count: 34, region: "Japan" },
    { name: "Amalfi Coast", count: 12, region: "Italy" },
    { name: "New York", count: 19, region: "New York" }
  ]
};

// Review stub map for cross-linking
window.JR_BY_SLUG = Object.fromEntries(window.JR_DATA.reviews.map(r => [r.slug, r]));
